Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -57,38 +57,22 @@ runs:
         cat task-definition.json
       shell: bash
       
-    # - id: render-task-definition
-    #   uses: aws-actions/amazon-ecs-render-task-definition@v1.6.1
-    #   with:
-    #     task-definition: task-definition.json
-    #     container-name: app
-    #     image: "${{ steps.login_ecr.outputs.registry }}/${{ inputs.image_name }}:${{ inputs.tag }}"
-
-    # - name: deploy the task definition to AWS
-    #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
-    #   with:
-    #     task-definition: task-definition.json
-    #     cluster: production
-    #     run-task: false
-    
-    
-    
-    # - uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.1
-    #   id: ecs-deploy
-    #   with:
-    #     task-definition: task-definition.json
-    #     service: ${{ inputs.ecs_service }}
-    #     cluster: ${{ inputs.ecs_cluster }}
-    #     wait-for-service-stability: true
-
-    # - id: check-deployment
-    #   run: |
-    #      CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ inputs.ecs_cluster }} --services ${{ inputs.ecs_service }} --query services[0].deployments[0].taskDefinition | jq -r ".")
-    #      NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
-    #      echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-    #      echo "New task arn: $NEW_TASK_DEF_ARN"
-    #      if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-    #        echo "Deployment failed."
-    #        exit 1
-    #      fi
-    #   shell: bash
+    - uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.1
+      id: ecs-deploy
+      with:
+        task-definition: task-definition.json
+        service: ${{ inputs.ecs_service }}
+        cluster: ${{ inputs.ecs_cluster }}
+        wait-for-service-stability: true
+        
+    - id: check-deployment
+      run: |
+         CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ inputs.ecs_cluster }} --services ${{ inputs.ecs_service }} --query services[0].deployments[0].taskDefinition | jq -r ".")
+         NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
+         echo "Current task arn: $CURRENT_TASK_DEF_ARN"
+         echo "New task arn: $NEW_TASK_DEF_ARN"
+         if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
+           echo "Deployment failed."
+           exit 1
+         fi
+      shell: bash
